### ISSUE TITLE
feature request: automatic lua module resolution

### ISSUE THREAD

**Issue by horriblename** [nvim-neorocks/lz.n#39]
Hi, I wrote a plugin that automatically loads opt/ plugins if they're not found in runtimepath.

https://github.com/horriblename/lzn-auto-require

I'm wondering if you would be interested in something like this in lz.n itself?

**Comment by mrcjkb** [comment]
Hey 👋 

Thanks for the suggestion.
Auto-loading on `require` is out of scope for this library, as it's incredibly difficult (probably impossible) to get 100 % right.

But I'd be happy to link to your project in the readme 😀

P.S. lz.n provides [an API for registering custom handlers](https://github.com/nvim-neorocks/lz.n?tab=readme-ov-file#custom-handlers).

[Here's an example](https://github.com/BirdeeHub/birdeeSystems/blob/a38a1c2d9b8d4b44382eba094d3504817c8a3296/common/birdeevim/lua/birdee/on_require.lua) where @BirdeeHub used it to do the same thing. 
Perhaps both of you can join forces? 😀

**Comment by mrcjkb** [comment]
https://github.com/nvim-neorocks/lz.n?tab=readme-ov-file#extensions

**Comment by horriblename** [comment]
thanks for the tips!

> Auto-loading on require is out of scope for this library, as it's incredibly difficult (probably impossible) to get 100 % right.

could you elaborate a little more? A link or something would be fine, so I can know what to expect

**Comment by mrcjkb** [comment]
There haven't been any publications on the topic 😅

It's just that it's impossible for lz.n or a user to know which modules a plugin might expose (now or in the future) and which of those another plugin might try to `require`. So a `lz.n.Handler` would have to make assumptions about that.

Your plugin searches for modules on the packpath, which is reliable *if a plugin is on the packpath*. But lz.n itself doesn't make any assumptions about where plugins are installed or how they are loaded. That's why you can pass in any function to load plugins. It just defaults to `packadd` for convenience.

**Comment by BirdeeHub** [comment]
Can confirm, this is why in mine the user specifies the top level modules that can trigger loading

**Comment by BirdeeHub** [comment]
You could try modifying the one I showed to search the lua directory of the plugin for all the top level modules and add them automatically instead of taking a list?
